package dasturlash.userservice

enum class ErrorCode(val code: Int, val message: String) {
    USER_NOT_FOUND_EXCEPTION(100, "USER_NOT_FOUND_EXCEPTION"),
    EMAIL_ALREADY_EXISTS(102, "EMAIL_ALREADY_EXISTS"),
    USERNAME_ALREADY_EXISTS(103, "USERNAME_ALREADY_EXISTS"),
    USER_ALREADY_FOLLOWED(104, "USER_ALREADY_FOLLOWED"),

}

enum class UserStatus {
    ACTIVE, INACTIVE, PENDING, REJECTED, BLOCK
}

enum class UserRole{
    ROLE_ADMIN, ROLE_USER, ROLE_PUBLISHER
}