package dasturlash.userservice

enum class ErrorCode(val code: Int, val message: String) {
    USER_NOT_FOUND_EXCEPTION(100, "USER_NOT_FOUND_EXCEPTION"),
    EMAIL_ALREADY_EXISTS(102, "EMAIL_ALREADY_EXISTS"),
    USERNAME_ALREADY_EXISTS(103, "USERNAME_ALREADY_EXISTS"),
    USER_ALREADY_FOLLOWED_OR_SELF_FOLLOW(104, "USER_ALREADY_FOLLOWED"),
    USER_ALREADY_UNFOLLOWED_OR_SELF_UNFOLLOW(105, "USER_ALREADY_UNFOLLOWED_OR_SELF_UNFOLLOW"),
    FOLLOWING_OR_UNFOLLOWING_USER_NOT_FOUND(106, "FOLLOWING_OR_UNFOLLOWING_USER_NOT_FOUND"),

}

enum class UserStatus {
    ACTIVE, INACTIVE, PENDING, REJECTED, BLOCK
}

enum class UserRole{
    ROLE_ADMIN, ROLE_USER, ROLE_PUBLISHER
}